[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
lean-buffer = { path = "../../lean_buffer" }
flatbuffers = "23.1.21"
objectbox = { path = "../" }
serial_test = "1.0.0"

[build-dependencies]
objectbox = { path = "../" }
