[package]
name = "objectbox"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
objectbox-macros = { path = "macros" }
objectbox-generator = { path = "generator" }
chrono = "0.4"

[build-dependencies]
bindgen = "^0.51"

