[package]
name = "objectbox"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder = { path = "builder" }
chrono = "0.4"

[build-dependencies]
bindgen = "^0.51"


