[package]
name = "objectbox"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
objectbox-macros = { path = "macros" }
objectbox-generator = { path = "generator" }
chrono = "0.4"
flatbuffers = "22.10.26"
bytebuffer = "2.0.1"
anymap = "0.12.1"

[build-dependencies]
bindgen = "^0.51"

