name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Install ObjectBox C-API
      run: ./install.sh
    - name: Run tests
      run: cargo test --verbose
